name: Linux builds (simple)

on: [push, pull_request]

jobs:
  build:
    name: ${{matrix.os}}, C++14, ${{matrix.build_type}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-2019, windows-2022]
        platform: [Win32, x64]
        build_type: [Debug, Release]
    steps:
      - uses: actions/checkout@v2
      
      - name: Configure build
        working-directory: ${{runner.workspace}}
        run: |
          cmake -S . -B ${{runner.workspace}}/build \
                -DCMAKE_CXX_STANDARD=14 \
                -A ${{matrix.platform}} \
                --preset all-tests
      
      - name: Build tests
        working-directory: ${{runner.workspace}}
        run: |
          $jobs = (Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors
          cmake --build build --parallel $jobs
      
      - name: Run tests
        working-directory: ${{runner.workspace}}/build
        env:
            CTEST_OUTPUT_ON_FAILURE: 1
        run: |
          $jobs = (Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors
          ctest -C ${{matrix.build_type}} -j $jobs
